/I..\..\include\animator
/I..\..\include\config
/I..\..\include\core
/I..\..\include\effects
/I..\..\include\images
/I..\..\include\ports
/I..\..\include\svg
/I..\..\include\text
/I..\..\include\utils
/I..\..\include\views
/I..\..\include\xml
/I..\..\src\animator
/I..\..\src\config
/I..\..\src\core
/I..\..\src\effects
/I..\..\src\images
/I..\..\src\ports
/I..\..\src\svg
/I..\..\src\text
/I..\..\src\utils
/I..\..\src\views
/I..\..\src\xml

/DSK_BUILD_FOR_WIN32
